import { describe, expect, it } from 'vitest'

import { readDashboardFixture } from './test-fixtures/operatorHudTestFixtures'

describe('public BESS narrative architecture', () => {
  it('renders the public route from live committed GitHub JSON artifacts', () => {
    const page = readDashboardFixture('../pages/ukraine-bess-arbitrage-index.vue')
    const field = readDashboardFixture('../components/public/BessDispatchField.vue')
    const actionRail = readDashboardFixture('../components/public/BessActionPreviewRail.vue')

    expect(page).toContain('publicBessDataUrl(\'latest.json\')')
    expect(page).toContain('publicBessDataUrl(\'history.json\')')
    expect(page).toContain('publicBessDataUrl(\'forecast/latest.json\')')
    expect(page).toContain('publicBessDataUrl(\'forecast_scoreboard.json\')')
    expect(page).toContain('publicBessDataUrl(\'publication_status.json\')')
    expect(page).toContain('publicBessDataContentUrl(\'latest.json\')')
    expect(page).toContain('transform: parsePublicBessPayload')
    expect(page).toContain('<BessDispatchField')
    expect(page).toContain('<BessActionPreviewRail')
    expect(page).toContain(':realized-schedule="selectedSchedule"')
    expect(page).toContain(':forecast-models="models"')
    expect(page.indexOf('<BessActionPreviewRail')).toBeLessThan(page.indexOf('Price, Dispatch &amp; SoC'))
    expect(page).toContain('SVG evidence charts below remain the analytical source of truth')
    expect(page).toContain('GitHub: transparent source of truth')
    expect(page).not.toContain('Autonomous publication path')
    expect(page).not.toContain('GitHub Actions publishes source-backed JSON')
    expect(page).not.toContain('GitHub to Vercel publication lane')
    expect(page).toContain('robots: \'index, follow, max-image-preview:large\'')
    expect(page).toContain('rel: \'sitemap\'')
    expect(page).toContain('href: `${siteUrl}/llms.txt`')
    expect(page).toContain('\'@type\': \'Dataset\'')
    expect(page).toContain('\'@type\': \'WebSite\'')
    expect(page).toContain('OREE Day-Ahead Market public price rows')
    expect(page).toContain('const ogImageUrl = `${siteUrl}/og/ukraine-bess-arbitrage-index.png`')
    expect(page).toContain('ogImage: ogImageUrl')
    expect(page).toContain('twitterImage: ogImageUrl')
    expect(page).toContain('property: \'og:image:width\'')
    expect(page).toContain('property: \'og:image:height\'')

    expect(field).toContain('await import(\'three\')')
    expect(field).toContain('prefers-reduced-motion: reduce')
    expect(field).toContain('visibilitychange')
    expect(field).toContain('Math.min(window.devicePixelRatio || 1, 1.5)')
    expect(field).toContain('aria-pressed')
    expect(field).toContain('viewModeOptions')
    expect(field).toContain('setViewMode')
    expect(field).toContain('viewMode.value === \'plan\'')
    expect(actionRail).toContain('props.realizedSchedule.slice(0, 24)')
    expect(actionRail).toContain('forecastPointsRaw.value.slice(0, 2)')
    expect(actionRail).toContain('class="bess-action-preview__item"')
    expect(actionRail).toContain('role="listitem"')
    expect(actionRail).toContain('Forecast price-signal preview')
    expect(actionRail).toContain('No bids generated')
    expect(actionRail).toContain('not_emitted')
    expect(actionRail).toContain('public_bess_arbitrage_index_not_market_execution')
  })

  it('resets reload scroll on the public narrative route without relying on section hashes', () => {
    const page = readDashboardFixture('../pages/ukraine-bess-arbitrage-index.vue')

    expect(page).toContain('bess-index-initial-scroll-reset')
    expect(page).toContain('window.history.scrollRestoration = \'manual\'')
    expect(page).toContain('var shouldReset = window.location.hash || (navigation && navigation.type ===')
    expect(page).toContain('const shouldReset = Boolean(window.location.hash) || navigation?.type ===')
    expect(page).toContain('scheduleInitialTopScroll')
    expect(page).toContain('document.documentElement.scrollTop = 0')
    expect(page).toContain('document.body.scrollTop = 0')
    expect(page).toContain('const activeSection = ref(\'index\')')
    expect(page).toContain('startSectionObserver')
    expect(page).toContain('IntersectionObserver')
    expect(page).toContain('activeSection === \'forecast\' ? \'page\' : undefined')
    expect(page).toContain('@click.prevent="navigateToSection(\'forecast\')"')
    expect(page).toContain('@click.prevent="navigateToSection(\'methodology\')"')
  })

  it('keeps the responsive public hero as a lead-generation surface', () => {
    const page = readDashboardFixture('../pages/ukraine-bess-arbitrage-index.vue')
    const css = readDashboardFixture('../assets/css/bess-index.css').replace(/\r\n/g, '\n')
    const field = readDashboardFixture('../components/public/BessDispatchField.vue')
    const actionRail = readDashboardFixture('../components/public/BessActionPreviewRail.vue')

    expect(page).toContain('Let\'s connect')
    expect(page).toContain('mailto:')
    expect(page).toContain('bess-index-workbench')
    expect(page).toContain('workbenchModels')
    expect(page).toContain('workbenchStages')
    expect(page).toContain('Index evidence, forecast, and lead overview')
    expect(page).not.toContain('bess-workbench-panel--ladder')
    expect(page).toContain('bess-story-connect-panel')
    expect(page).toContain('bess-story-connect__receipt')
    expect(page).toContain('bess-story-connect__action-card')
    expect(page).toContain('bess-lead-action-list')
    expect(page).toContain('bess-hero-preset-switcher')
    expect(page).toContain('bess-battery-preset-switcher')
    expect(page).toContain('bess-hero-evidence-stack')
    expect(page).toContain('bess-hero-source-card')
    expect(page).toContain('bess-hero-dispatch-legend')
    expect(page).toContain('dispatchHoverIndex')
    expect(page).toContain('dispatchActivePoint')
    expect(page).toContain('bess-svg-active-ripple')
    expect(page).toContain('bess-svg-tooltip')
    expect(page).toContain('bess-svg-hit')
    expect(page).toContain('dispatchSvg.socLine')
    expect(page).toContain('bess-svg-line--soc')
    expect(page).toContain('bess-svg-label--soc')
    expect(page).toContain('SOC {{')
    expect(page).toContain('bess-chart-data-table')
    expect(page).toContain('BessActionPreviewRail')
    expect(page).toContain('24-hour BESS dispatch schedule evidence')
    expect(page).toContain('OREE (Оператор ринку)')
    expect(page).toContain('Day-Ahead Market (DAM) · OES Ukraine')
    expect(css).toContain('container-name: bess-hero-copy')
    expect(css).toContain('container-name: bess-hero-stage')
    expect(css).toContain('container-name: bess-index-workbench')
    expect(css).toContain('.bess-story-connect-panel')
    expect(css).toContain('.bess-story-connect__receipt')
    expect(css).toContain('.bess-story-connect__action-card')
    expect(css).toContain('.bess-battery-preset-switcher')
    expect(css).toContain('Compact responsive proof surface')
    expect(css).toContain('"receipt"\n      "stage"\n      "metrics"')
    expect(css).toContain('grid-template-columns: minmax(0, 1fr) max-content')
    expect(css).toContain('Mobile side receipts use a compact grid, not a clipped horizontal rail.')
    expect(css).toContain('Intermediate tablet side receipts: prevent narrow right-rail values from clipping.')
    expect(css).toContain('@media (max-width: 1500px) and (min-width: 1181px)')
    expect(css).toContain('.bess-public-shell--narrative .bess-hero-side .bess-side-card:nth-child(3)')
    expect(css).toContain('grid-column: 1 / -1')
    expect(css).toContain('First-screen density tuning: keep the academic receipt surface light and scannable.')
    expect(css).toContain('Mobile evidence-first ordering: mirror the desktop concept with receipt before the field.')
    expect(css).toContain('Concept alignment pass: active sticky navigation, lighter academic typography, calmer evidence chrome.')
    expect(css).toContain('width: min(1700px, calc(100% - 40px))')
    expect(css).toContain('.bess-public-shell--narrative .bess-public-nav a[aria-current=\'page\']')
    expect(css).toContain('mask-image: linear-gradient(90deg, #000 0, #000 calc(100% - 28px), transparent 100%)')
    expect(css).toContain('Academic type-rhythm pass: separate the condensed brand from the readable Noto Serif hero.')
    expect(css).toContain('font-family: var(--bess-font-hero)')
    expect(css).toContain('font-size: 38px')
    expect(css).toContain('Lower receipt polish: reduce dashboard heaviness and keep panels aligned to the academic concept.')
    expect(css).toContain('Receipt ledger alignment pass: closer to the concept single-sheet evidence strip.')
    expect(css).toContain('Concept fidelity pass: wider evidence fields, stronger receipt icons, interactive SVG affordances.')
    expect(css).toContain('grid-template-rows: 64px 404px auto')
    expect(css).toContain('.bess-sr-only')
    expect(css).toContain('grid-template-columns: minmax(340px, 0.5fr) minmax(760px, 1.84fr) minmax(170px, 0.22fr)')
    expect(css).toContain('grid-template-columns: minmax(0, 1.32fr) minmax(230px, 0.24fr)')
    expect(css).toContain('@keyframes bessSvgRipple')
    expect(css).toContain('.bess-svg-active-point')
    expect(css).toContain('Evidence chart encoding pass: DAM price blue, dispatch blue/yellow, SOC green.')
    expect(css).toContain('.bess-public-shell--narrative .bess-svg-line--soc')
    expect(css).toContain('.bess-public-shell--narrative .bess-svg-active-point--soc')
    expect(css).toContain('.bess-public-shell--narrative .bess-metric-grid--rail .bess-metric svg')
    expect(css).toContain('.bess-public-shell--narrative .bess-score-primary--light > .iconify')
    expect(css).toContain('.bess-public-shell--narrative .bess-metric-grid--rail .bess-metric > .iconify')
    expect(css).toContain('width: 25px')
    expect(css).toContain('container: bess-kpi-rail / inline-size')
    expect(css).toContain('@container bess-kpi-rail (max-width: 720px)')
    expect(css).toContain('.bess-public-shell--narrative .bess-workbench-panel')
    expect(css).toContain('min-height: 166px')
    expect(css).toContain('font-family: var(--bess-font-detail)')
    expect(css).toContain('min-height: 176px')
    expect(css).toContain('min-height: 68px')
    expect(css).toContain('min-height: 54px')
    expect(css).toContain('First-screen dispatch focus: give the WebGL field the same visual gravity as the concept.')
    expect(css).toContain('First-viewport receipt docking: keep the status strip visually attached to the dispatch field.')
    expect(css).toContain('align-self: end')
    expect(css).toContain('grid-template-columns: minmax(400px, 0.62fr) minmax(760px, 1.52fr) minmax(190px, 0.28fr)')
    expect(css).toContain('min-height: 430px')
    expect(css).toContain('height: 100%')
    expect(css).toContain('min-height: 300px')
    expect(css).toContain('min-height: 42px')
    expect(css).toContain('min-height: 44px')
    expect(css).toContain('background: rgba(255, 255, 255, 0.54)')
    expect(css).toContain('Source-and-legend rail pass: restore the concept\'s left evidence cards without changing data claims.')
    expect(css).toContain('.bess-hero-evidence-stack')
    expect(css).toContain('.bess-hero-source-card')
    expect(css).toContain('.bess-hero-dispatch-legend')
    expect(css).toContain('@container bess-hero-copy (min-width: 360px)')
    expect(css).toContain('grid-template-columns: minmax(0, 1fr) minmax(180px, 0.58fr)')
    expect(css).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(css).toContain('scroll-snap-type: inline mandatory')
    expect(css).toContain('overscroll-behavior-inline: contain')
    expect(css).toContain('Data-theatre refinement: unify the first viewport into one academic instrument panel.')
    expect(css).toContain('grid-template-columns: minmax(610px, 1.16fr) minmax(320px, 0.42fr) minmax(350px, 0.48fr)')
    expect(css).toContain('height: 260px')
    expect(css).toContain('min-height: 448px')
    expect(css).toContain('margin-block-start: 34px')
    expect(css).toContain('drop-shadow(0 0 12px rgba(12, 126, 179, 0.08))')
    expect(css).toContain('Proof-to-contact funnel polish: make the public evidence path feel like one portfolio-grade receipt.')
    expect(css).toContain('container: bess-lead-funnel / inline-size')
    expect(css).toContain('container: bess-proof-funnel / inline-size')
    expect(css).toContain('grid-template-columns: minmax(340px, 0.74fr) minmax(480px, 1.05fr) minmax(250px, 0.45fr)')
    expect(css).toContain('@container bess-lead-funnel (max-width: 980px)')
    expect(css).toContain('contain: layout style paint')
    expect(css).toContain('Dispatch evidence theatre pass: align the 3D field, compact figure, and full receipt graph into one marker language.')
    expect(css).toContain('container: bess-dispatch-proof / inline-size')
    expect(css).toContain('grid-template-columns: minmax(760px, 1fr) minmax(260px, 0.31fr)')
    expect(css).toContain('height: 372px')
    expect(css).toContain('minmax(680px, 1.28fr) minmax(300px, 0.4fr) minmax(330px, 0.44fr)')
    expect(css).toContain('Forecast trust rail pass: make forecast lanes and promotion ladder read as source-backed receipts.')
    expect(css).toContain('Browser annotation QA pass: hover receipts, wider hero theatre, and public-facing receipt polish.')
    expect(css).toContain('.bess-hero-preset-switcher')
    expect(css).toContain('button[aria-pressed=\'true\']')
    expect(css).toContain('grid-template-columns: minmax(320px, 0.44fr) minmax(900px, 2.14fr) minmax(178px, 0.2fr)')
    expect(css).toContain('.bess-lead-action-list')
    expect(css).toContain('.bess-footer-note a')
    expect(css).toContain('container: bess-trust-panel / inline-size')
    expect(css).toContain('counter-reset: bess-lane')
    expect(css).toContain('grid-template-columns: 28px minmax(0, 1fr) auto')
    expect(css).toContain('box-shadow:\n    inset 3px 0 0 rgba(12, 126, 179, 0.42)')
    expect(css).toContain('.bess-public-shell--narrative .bess-concept-ladder li:first-child')
    expect(css).toContain('@container bess-trust-panel (max-width: 340px)')
    expect(field).toContain('container-name: bess-field')
    expect(field).toContain('@container bess-field')
    expect(field).toContain('annotationIndex')
    expect(field).toContain('annotationPoint')
    expect(field).toContain('bess-field-annotation')
    expect(field).toContain('@pointerleave="clearAnnotation"')
    expect(field).toContain('left: var(--bess-marker-x)')
    expect(field).toContain('top: var(--bess-marker-y)')
    expect(field).toContain('box-shadow:')
    expect(field).toContain('0 0 0 6px rgba(10, 119, 168, 0.08)')
    expect(actionRail).toContain('Operator-style preview')
    expect(actionRail).toContain('Want this calibrated?')
    expect(actionRail).toContain('Turn the public receipt into a private facility review.')
    expect(actionRail).toContain('Discuss setup')
    expect(actionRail).toContain('bess-action-chip--preview')
    expect(actionRail).toContain('aria-pressed')
    expect(actionRail).toContain('Charge watch')
    expect(actionRail).toContain('Discharge watch')
    expect(actionRail).toContain('Hold watch')
    expect(actionRail).toContain('claimBoundaryLabel')
    expect(actionRail).toContain('proposedBidStatusLabel')
  })

  it('keeps the public page on the selected retro academic font system', () => {
    const nuxtConfig = readDashboardFixture('../../nuxt.config.ts')
    const tokens = readDashboardFixture('../assets/css/design-tokens.foundation.css')
    const css = readDashboardFixture('../assets/css/bess-index.css')
    const field = readDashboardFixture('../components/public/BessDispatchField.vue')

    expect(nuxtConfig).toContain('Alumni+Sans')
    expect(nuxtConfig).toContain('Advent+Pro')
    expect(nuxtConfig).toContain('Anonymous+Pro')
    expect(nuxtConfig).toContain('Noto+Sans')
    expect(nuxtConfig).toContain('Noto+Sans+Mono')
    expect(nuxtConfig).toContain('Noto+Serif')
    expect(nuxtConfig).toContain('subset=latin,cyrillic')
    expect(nuxtConfig).toMatch(/ui:\s*\{\s*fonts: false\s*\}/)
    expect(tokens).toContain('--font-sans: \'Noto Sans\'')
    expect(tokens).toContain('--font-mono: \'Noto Sans Mono\'')
    expect(css).toContain('--bess-font-brand: "Alumni Sans"')
    expect(css).toContain('--bess-font-hero: "Noto Serif"')
    expect(css).toContain('--bess-font-display: "Advent Pro"')
    expect(css).toContain('--bess-font-ui: "Advent Pro"')
    expect(css).toContain('--bess-font-data: "Anonymous Pro", "Noto Sans Mono"')
    expect(css).toContain('--bess-font-detail: "Noto Sans", "Noto Sans Mono"')
    expect(css).toContain('--bess-weight-data: 700')
    expect(css).toContain('BESS typography pass: Alumni brand, Noto Serif hero, Advent controls/display, Anonymous numeric receipts, Noto body.')
    expect(css).toContain('Academic type-rhythm pass: separate the condensed brand from the readable Noto Serif hero.')
    expect(css).toContain('font-family: var(--bess-font-hero)')
    expect(css).toContain('font-family: var(--bess-font-detail)')
    expect(css).toContain('text-wrap: balance')
    expect(css).toContain('text-wrap: pretty')
    expect(css).toContain('font-optical-sizing: auto')
    expect(css).toContain('font-synthesis-style: none')
    expect(css).toContain('font-size: 38px')
    expect(css).toContain('font-size: 26px')
    expect(css).toContain('font-variant-numeric: tabular-nums')
    expect(css).toContain('font-feature-settings: "tnum" 1, "zero" 1')
    expect(css).toContain('font-size-adjust: from-font')
    expect(css).toContain('@supports not (font-size-adjust: from-font)')
    expect(css).toContain('.bess-hero-receipt strong')
    expect(css).toContain('.bess-public-shell--narrative .bess-proof-strip')
    expect(css).toContain('min-height: 50px')
    expect(css).toContain('font-family: var(--bess-font-data)')
    expect(css).not.toContain('font-family: Georgia')
    expect(css).not.toContain('font-family: ui-monospace')
    expect(field).toContain('font-family: var(--bess-font-detail')
    expect(field).toContain('font-size-adjust: from-font')
    expect(field).toContain('var(--bess-font-data')
    expect(field).not.toContain('font-family: ui-monospace')
  })

  it('publishes crawl and agent discovery files for the public custom domain', () => {
    const nuxtConfig = readDashboardFixture('../../nuxt.config.ts')
    const indexPage = readDashboardFixture('../pages/index.vue')
    const robots = readDashboardFixture('../../public/robots.txt')
    const sitemap = readDashboardFixture('../../public/sitemap.xml')
    const llms = readDashboardFixture('../../public/llms.txt')
    const humans = readDashboardFixture('../../public/humans.txt')
    const indexNowKey = readDashboardFixture('../../public/7f5ab6c35c1f4c40b2e720377ab7fe19.txt')
    const readme = readDashboardFixture('../../../README.md')

    expect(nuxtConfig).toContain('\'https://energy-index.full-iron.com\'')
    expect(indexPage).toContain('navigateTo(\'/ukraine-bess-arbitrage-index\', { redirectCode: 301 })')
    expect(robots).toContain('Sitemap: https://energy-index.full-iron.com/sitemap.xml')
    expect(sitemap).toContain('<loc>https://energy-index.full-iron.com/ukraine-bess-arbitrage-index</loc>')
    expect(sitemap).toContain('xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"')
    expect(sitemap).toContain('<image:loc>https://energy-index.full-iron.com/og/ukraine-bess-arbitrage-index.png</image:loc>')
    expect(sitemap).toContain('<loc>https://energy-index.full-iron.com/forecast-challenge</loc>')
    expect(llms).toContain('Canonical public URL: https://energy-index.full-iron.com/ukraine-bess-arbitrage-index')
    expect(llms).toContain('market_execution_enabled=false')
    expect(llms).toContain('No YASNO/DTEK integration claim.')
    expect(humans).toContain('Boundary: public demo only.')
    expect(indexNowKey.trim()).toBe('7f5ab6c35c1f4c40b2e720377ab7fe19')
    expect(readme).toContain('https://energy-index.full-iron.com/ukraine-bess-arbitrage-index')
    expect(readme).toContain('post-defense public demo')
    expect(readme).toContain('not the defended private operator functionality')
  })

  it('keeps the Three.js field evidence-bearing instead of decorative only', () => {
    const field = readDashboardFixture('../components/public/BessDispatchField.vue')

    expect(field).toContain('floorStrips')
    expect(field).toContain('priceCurtains')
    expect(field).toContain('signalMarkers')
    expect(field).toContain('Peak price')
    expect(field).toContain('Low price')
    expect(field).toContain('Largest move')
    expect(field).toContain('bess-field__signal-stack')
    expect(field).toContain('\'bess-field__signal\'')
    expect(field).toContain('aria-label="Dispatch field signal shortcuts"')
    expect(field).toContain(':style="selectedPositionStyle"')
    expect(field).toContain('Academic field overlay polish: keep evidence labels visible, but reduce HUD weight.')
    expect(field).toContain('background-color: rgba(255, 255, 255, 0.42)')
    expect(field).toContain('font-size: 7.5px')
    expect(field).toContain('min-height: 36px')
    expect(field).toContain('Concept-grade 3D field polish: make the canvas the hero, keep overlays quiet.')
    expect(field).toContain('new THREE.HemisphereLight')
    expect(field).toContain('new THREE.MeshPhysicalMaterial')
    expect(field).toContain('renderer.toneMapping = THREE.ACESFilmicToneMapping')
    expect(field).toContain('renderer.shadowMap.type = THREE.PCFShadowMap')
    expect(field).toContain('new THREE.Fog')
    expect(field).toContain('new objects.THREE.TubeGeometry')
    expect(field).toContain('priceGlow')
    expect(field).toContain('priceSurface')
    expect(field).toContain('socRibbon')
    expect(field).toContain('fieldFrame')
    expect(field).toContain('priceWall')
    expect(field).toContain('selectionBeam')
    expect(field).toContain('selectionNeedle')
    expect(field).toContain('selectionCap')
    expect(field).toContain('fieldFrameGeometryFor')
    expect(field).toContain('priceWallGeometryFor')
    expect(field).toContain('smoothSocPoints')
    expect(field).toContain('stateRibbonGeometryFor')
    expect(field).toContain('pricePressureSurfaceGeometryFor')
    expect(field).toContain('numberValue(props.capacityMwh)')
    expect(field).toContain('SOC state')
    expect(field).toContain('new THREE.CylinderGeometry(0.165, 0.19, 1, 28, 1)')
    expect(field).toContain('new THREE.CatmullRomCurve3')
    expect(field).toContain('markerPositionStyle')
    expect(field).toContain('In-field signal pins: keep shortcuts, remove card clutter from the 3D plane.')
    expect(field).toContain('left: clamp(132px, calc(var(--bess-selected-x) - 90px), calc(100% - 210px))')
    expect(field).toContain('background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.16)')
    expect(field).toContain('.bess-field__hour::before')
    expect(field).toContain('const holdHeight = 0.48 + priceNormalized * 0.92')
    expect(field).toContain('const radiusLift = isHold ? 0.98 : 0.96')
    expect(field).toContain('const laneZ = isHold ? 0.02 : power >= 0 ? -0.33 : 0.33')
    expect(field).toContain('bar.userData.isHold = isHold')
    expect(field).toContain('material.opacity = isSelected ? 0.8 : 0.66')
    expect(field).toContain('material.opacity = isSelected ? 0.9 : 0.76')
    expect(field).toContain('emissiveIntensity = isSelected ? 0.1 : 0')
    expect(field).toContain('Math.sqrt(normalizedPower) * 1.32')
    expect(field).toContain('selectNearestHourFromPointer')
    expect(field).toContain('handleFieldPointerDown')
    expect(field).toContain('handleFieldPointerMove')
    expect(field).toContain('handleFieldWheel')
    expect(field).toContain('@pointerdown="handleFieldPointerDown"')
    expect(field).toContain('@wheel="handleFieldWheel"')
    expect(field).toContain('interactionRotation')
    expect(field).toContain('interactionZoom')
    expect(field).toContain('renderSceneNow')
    expect(field).toContain('nudgeOrbit')
    expect(field).toContain('resetOrbit')
    expect(field).toContain('bess-field__orbit-controls')
    expect(field).toContain('aria-label="Dispatch field orbit controls"')
    expect(field).toContain('Rotate dispatch field left')
    expect(field).toContain('Reset dispatch field view')
    expect(field).toContain('Rotate dispatch field right')
    expect(field).toContain('i-lucide-rotate-ccw')
    expect(field).toContain('i-lucide-locate-fixed')
    expect(field).toContain('i-lucide-rotate-cw')
    expect(field).toContain('Drag to rotate')
    expect(field).toContain('Scroll to zoom')
    expect(field).toContain('numberValue(row.net_value_uah)')
    expect(field).toContain('min-height: 34px')
    expect(field).toContain('min-height: 24px')
    expect(field).toContain('background-color: rgba(255, 255, 255, 0.34)')
    expect(field).toContain('filter: saturate(1.1) contrast(1.03)')
    expect(field).toContain('Dispatch field density pass: make the WebGL evidence plane read closer to the reference concept.')
    expect(field).toContain('Concept-depth Three.js pass: price wall, translucent curtains, and selected-hour needle.')
    expect(field).toContain('@keyframes bessFieldRipple')
    expect(field).toContain('button.is-selected::after')
    expect(field).toContain('filter: saturate(1.24) contrast(1.08)')
  })

  it('keeps the public claim boundary explicit and non-executing', () => {
    const page = readDashboardFixture('../pages/ukraine-bess-arbitrage-index.vue')
    const actionRail = readDashboardFixture('../components/public/BessActionPreviewRail.vue')

    expect(page).toContain('No market execution')
    expect(page).toContain('not_market_execution')
    expect(page).toContain('not_emitted')
    expect(actionRail).toContain('Public read-model only')
    expect(actionRail).toContain('not private operator commands')
    expect(actionRail).toContain('No bids generated')
    expect(actionRail).toContain('not_emitted')
    expect(page).toContain('DT / HF DT challenger')
    expect(page).toContain('never default market execution')
    expect(page).not.toContain('Market bids generated')
    expect(page).not.toContain('Forecast guaranteed')
    expect(page).not.toContain('DT controller deployed')
    expect(actionRail).not.toContain('Market bids generated')
    expect(actionRail).not.toContain('Forecast guaranteed')
    expect(actionRail).not.toContain('DT controller deployed')
    expect(actionRail).not.toContain('market instruction')
    expect(actionRail).not.toContain('execute')
  })

  it('covers published, blocked, and empty forecast artifact states', () => {
    const page = readDashboardFixture('../pages/ukraine-bess-arbitrage-index.vue')
    const latest = JSON.parse(readDashboardFixture('../../public/data/bess-arbitrage-index/latest.json'))
    const forecast = JSON.parse(readDashboardFixture('../../public/data/bess-arbitrage-index/forecast/latest.json'))
    const scoreboard = JSON.parse(readDashboardFixture('../../public/data/bess-arbitrage-index/forecast_scoreboard.json'))
    const publicationStatus = JSON.parse(readDashboardFixture('../../public/data/bess-arbitrage-index/publication_status.json'))

    expect(latest.market_execution_enabled).toBe(false)
    expect(latest.proposed_bid_status).toBe('not_emitted')
    expect(latest.source.row_count).toBeGreaterThan(0)
    expect(latest.presets.length).toBeGreaterThan(0)

    expect(forecast.market_execution_enabled).toBe(false)
    expect(forecast.models.some((model: Record<string, unknown>) => model.backend_status === 'blocked')).toBe(true)
    expect(page).toContain('bess-status--blocked')
    expect(page).toContain('model.backend_status ===')

    expect(scoreboard.row_count).toBe(0)
    expect(scoreboard.rows).toEqual([])
    expect(publicationStatus.realized.is_current_for_kyiv_schedule).toBe(true)
    expect(publicationStatus.forecast.is_current_for_kyiv_schedule).toBe(true)
    expect(publicationStatus.autonomy.compute_layer).toBe('github_actions_scheduled_static_json')
    expect(page).toContain('No scored forecast pairs yet.')
  })
})
